### ISSUE TITLE
求助！！！elementui组件中的中文换成韩文怎么操作

### ISSUE THREAD

**Issue by mf04** [KYX1234/Element-Admin#71]
![QQ截图20240107120229](https://github.com/KYX1234/Element-Admin/assets/89952128/b418ea63-c5bd-4f2a-89e9-05a146d27b46)

**Comment by KYX1234** [comment]
我想你可以试试这样
![image](https://github.com/KYX1234/Element-Admin/assets/77819037/4ea71098-2d88-4731-9a4d-0fee228ed0d5)
